### ISSUE TITLE
Remover aspas simples na linha 15 do index.js

### ISSUE THREAD

**Issue by Majortheus** [MatheusBrowz/GoStack_Conceitos_NodeJS#1]
Estava verificando como ficou seu index.js e aparentemente existe duas aspas simples que não fazem muito sentido dentro do contexto, até porque estão no inicio da linha sem serem chamadas por função nem nada, muito estranho, não sei se faltou algum push...

**Comment by MatheusBrowz** [comment]
Já foi corrigido, muito thx.
